import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Aeonik = localFont({
  src: [
    {
      path: "./fonts/AeonikTRIAL-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/AeonikTRIAL-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Aeonik-Medium.otf",
      weight: "500",
      style: "normal",
    },

    {
      path: "./fonts/AeonikTRIAL-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});
export const metadata: Metadata = {
  title: "Knox Locker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${Aeonik.className}  w-full h-full `}>{children}</body>
    </html>
  );
}
